/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Blog/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Outliner: typeof import('./src/components/Blog/Outliner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide1: typeof import('./src/components/Swiper-slides/slide1.vue')['default']
    Slide2: typeof import('./src/components/Swiper-slides/slide2.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
